modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/Suff99/VRModel/issues"
license = "https://github.com/Suff99/VRModel/blob/main/LICENSE"

[[mods]]
modId = "vrgear"
version = "${version}"
displayName = "VR Gear"
authors = "Yermak, Teacup, Suff99"
description = '''
This mod applies Quest 2 headset and controllers models for your player model, just for visuals!
'''
logoFile = "vr_gear.png"

[[dependencies.vrgear]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vrgear]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"
